import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  display: "swap",
});

const gambrino = localFont({
  src: "./gambrino.woff2",
  variable: "--font-gambrino",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${raleway.variable} ${gambrino.variable} antialiased`}
    >
      <body className="bg-neutral-900 text-white">
        <Navbar />
        <main className="pt-14 md:pt-16">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
